# Generated by Django 3.0.7 on 2020-10-21 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
