# Generated by Django 3.0.7 on 2020-11-10 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_like_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
