# Generated by Django 3.0.7 on 2020-11-18 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20201115_2104'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='publish',
            new_name='publish_date',
        ),
    ]
