# Generated by Django 3.0.7 on 2020-09-14 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0012_auto_20200915_0031'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_applicant',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
