# Generated by Django 3.0.7 on 2020-10-15 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0014_job_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='location',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
