# Generated by Django 3.0.7 on 2020-10-15 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0015_job_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='image',
        ),
    ]
