# Generated by Django 3.0.7 on 2020-11-10 18:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0017_job_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='publish',
            field=models.DateField(default=datetime.datetime(2020, 11, 10, 18, 40, 20, 796438, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='published_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
