# Generated by Django 3.0.7 on 2020-11-22 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0018_auto_20201110_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='requirements',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
