# Generated by Django 3.0.7 on 2020-11-28 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0019_job_requirements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='publish',
            field=models.DateField(auto_now_add=True),
        ),
    ]
