# Generated by Django 3.0.7 on 2020-11-28 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0020_auto_20201128_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='publish',
            field=models.DateField(auto_now=True),
        ),
    ]
