# Generated by Django 3.0.7 on 2020-12-15 18:37

from django.db import migrations, models
import job.models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0021_auto_20201128_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='publish',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='job_applicant',
            name='cv',
            field=models.FileField(upload_to=job.models.file_upload),
        ),
    ]
